name: project-base

services:
  postgres:
    image: postgres
    container_name: project-base-postgres
    environment:
      POSTGRES_DB: project-base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5678:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
